### ISSUE TITLE
Loading Package Crashes Entire App

### ISSUE THREAD

**Issue by sahagin-dazs** [iDoRecall/meteor-referral#1]
I create a blank project and install the referral package and I get this error.

I also installed accounts-base and accounts-password to try and remediate with no luck.

/Users/admin/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
            throw(ex);
                  ^
ReferenceError: Accounts is not defined
    at Package (packages/idorecall_referral/packages/idorecall_referral.js:30:1)
    at Package (packages/idorecall_referral/packages/idorecall_referral.js:205:1)
    at /Users/admin/referraltest/test/.meteor/local/build/programs/server/packages/idorecall_referral.js:225:4
    at /Users/admin/referraltest/test/.meteor/local/build/programs/server/packages/idorecall_referral.js:234:3
    at /Users/admin/referraltest/test/.meteor/local/build/programs/server/boot.js:242:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/admin/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /Users/admin/referraltest/test/.meteor/local/build/programs/server/boot.js:137:5
Exited with code: 8
Your application is crashing. Waiting for file change.

**Comment by deeeed** [comment]
+1

**Comment by deeeed** [comment]
Ok so I ended up looking at the source and I would advise not using the package at all.
